import type { Role } from '@/lib/types'

export type ModuleDefinition = { id: string; title: string; group: string; description: string; roles: Role[]; dataPath: string; features: string[] }

export const moduleDefinitions: ModuleDefinition[] = [
  { id: 'overview', title: 'Tổng quan', group: 'Tổng quan', description: 'Chỉ số và công việc cần xử lý.', roles: ['admin','student-affairs','japan','training','teacher','dormitory','accounting','japan-partner'], dataPath: 'dashboardSnapshots', features: ['KPI theo role','Việc cần xử lý','Thông báo realtime'] },
  { id: 'student-list', title: 'Danh sách người học', group: 'Người học', description: 'Tìm kiếm, lọc và quản lý hồ sơ.', roles: ['admin','student-affairs','training','teacher','japan','japan-partner','accounting','dormitory'], dataPath: 'students', features: ['Tìm kiếm','Bộ lọc','Import CSV','CRUD hồ sơ'] },
  { id: 'student-profile', title: 'Hồ sơ người học', group: 'Người học', description: 'Thông tin cá nhân và lịch sử.', roles: ['admin','student-affairs','japan','japan-partner','accounting'], dataPath: 'studentProfiles', features: ['Thông tin cá nhân','Lịch sử đào tạo','File đính kèm','Timeline'] },
  { id: 'student-care', title: 'Chăm sóc người học', group: 'Người học', description: 'Yêu cầu hỗ trợ và nhắc việc.', roles: ['admin','student-affairs'], dataPath: 'studentCareTickets', features: ['Tạo ticket','Phân công','SLA','Trạng thái'] },
  { id: 'applications', title: 'Hồ sơ tuyển sinh', group: 'Tuyển sinh & Đơn hàng', description: 'Pipeline ứng viên và trạng thái hồ sơ.', roles: ['admin','student-affairs','japan','japan-partner'], dataPath: 'applications', features: ['Pipeline','Nguồn tuyển','Lịch sử liên hệ','Chuyển trạng thái'] },
  { id: 'orders', title: 'Đơn hàng tuyển dụng', group: 'Tuyển sinh & Đơn hàng', description: 'Vị trí, điều kiện và chỉ tiêu.', roles: ['admin','japan','japan-partner'], dataPath: 'recruitmentOrders', features: ['Vị trí tuyển','Chỉ tiêu','Điều kiện','Ứng viên phù hợp'] },
  { id: 'partners', title: 'Đối tác Nhật Bản', group: 'Tuyển sinh & Đơn hàng', description: 'Doanh nghiệp và lịch sử hợp tác.', roles: ['admin','japan','japan-partner'], dataPath: 'japanPartners', features: ['Doanh nghiệp','Đầu mối','Đơn hàng','Lịch sử hợp tác'] },
  { id: 'japan-workforce', title: 'Hồ sơ XKLĐ', group: 'Tuyển sinh & Đơn hàng', description: 'Tiến độ hồ sơ xuất khẩu lao động.', roles: ['admin','japan','japan-partner'], dataPath: 'japanApplications', features: ['Checklist hồ sơ','Tiến độ visa','Lịch phỏng vấn','File hồ sơ'] },
  { id: 'courses', title: 'Chương trình đào tạo', group: 'Đào tạo', description: 'Khung chương trình và học phần.', roles: ['admin','training','teacher'], dataPath: 'courses', features: ['Chương trình','Học phần','Phiên bản','Phê duyệt'] },
  { id: 'classes', title: 'Lớp học', group: 'Đào tạo', description: 'Danh sách lớp và giảng viên.', roles: ['admin','training','teacher'], dataPath: 'classes', features: ['Danh sách lớp','Phân công','Điểm danh','Sĩ số'] },
  { id: 'schedules', title: 'Lịch học', group: 'Đào tạo', description: 'Lịch phòng, lịch giảng và điểm danh.', roles: ['admin','training','teacher','student-affairs'], dataPath: 'classSchedules', features: ['Lịch ngày/tuần','Phòng học','Điểm danh','Realtime'] },
  { id: 'materials', title: 'Học liệu', group: 'Đào tạo', description: 'Tài liệu và phiên bản phát hành.', roles: ['admin','training','teacher'], dataPath: 'learningMaterials', features: ['Upload file','Phiên bản','Phân quyền file','Tìm kiếm'] },
  { id: 'exams', title: 'Ngân hàng đề thi', group: 'Khảo thí & Chứng chỉ', description: 'Câu hỏi, ma trận và phiên bản đề.', roles: ['admin','training','teacher'], dataPath: 'examBank', features: ['Ngân hàng câu hỏi','Ma trận đề','Trộn đề','Xuất đề'] },
  { id: 'exam-sessions', title: 'Kỳ thi', group: 'Khảo thí & Chứng chỉ', description: 'Lịch thi và phòng thi.', roles: ['admin','training','teacher'], dataPath: 'examSessions', features: ['Lịch thi','Phòng thi','Danh sách dự thi','Giám thị'] },
  { id: 'grading', title: 'Chấm điểm', group: 'Khảo thí & Chứng chỉ', description: 'Nhập, duyệt và khóa điểm.', roles: ['admin','training','teacher'], dataPath: 'grades', features: ['Nhập điểm','Duyệt điểm','Khóa điểm','Xuất bảng điểm'] },
  { id: 'certificates', title: 'Chứng chỉ', group: 'Khảo thí & Chứng chỉ', description: 'Phát hành và tra cứu chứng chỉ.', roles: ['admin','training','student-affairs'], dataPath: 'certificates', features: ['Cấp chứng chỉ','Mẫu chứng chỉ','Tra cứu','Thu hồi'] },
  { id: 'dormitory', title: 'Phòng ở', group: 'KTX & Dịch vụ', description: 'Sơ đồ phòng và công suất.', roles: ['admin','dormitory'], dataPath: 'dormitories/rooms', features: ['Sơ đồ phòng','Xếp phòng','Công suất','Trạng thái'] },
  { id: 'residences', title: 'Hợp đồng cư trú', group: 'KTX & Dịch vụ', description: 'Hợp đồng, kỳ hạn và phí.', roles: ['admin','dormitory','accounting'], dataPath: 'dormitories/contracts', features: ['Hợp đồng','Gia hạn','Phí ở','File ký kết'] },
  { id: 'service-tickets', title: 'Sự cố & yêu cầu', group: 'KTX & Dịch vụ', description: 'Tiếp nhận và phân công xử lý.', roles: ['admin','dormitory','student-affairs'], dataPath: 'serviceTickets', features: ['Tạo yêu cầu','Phân công','SLA','Đóng yêu cầu'] },
  { id: 'accounting', title: 'Thu chi', group: 'Tài chính', description: 'Phiếu thu, phiếu chi và đối soát.', roles: ['admin','accounting'], dataPath: 'accounting/transactions', features: ['Phiếu thu','Phiếu chi','Đối soát','Xuất báo cáo'] },
  { id: 'tuition', title: 'Học phí', group: 'Tài chính', description: 'Biểu phí và các khoản phải thu.', roles: ['admin','accounting','student-affairs'], dataPath: 'accounting/tuition', features: ['Biểu phí','Ghi nhận thanh toán','Biên lai','Thông báo'] },
  { id: 'debts', title: 'Công nợ', group: 'Tài chính', description: 'Theo dõi và nhắc công nợ.', roles: ['admin','accounting'], dataPath: 'accounting/debts', features: ['Công nợ','Nhắc hạn','Đối soát','Xuất danh sách'] },
  { id: 'bank-accounts', title: 'Tài khoản ngân hàng', group: 'Tài chính', description: 'Thông tin tài khoản ngân hàng ban quản trị.', roles: ['admin','accounting'], dataPath: 'accounting/bankAccounts', features: ['Danh sách TK','Loại tài khoản','Chi nhánh','Trạng thái'] },
  { id: 'reports', title: 'Báo cáo tổng hợp', group: 'Báo cáo & Điều hành', description: 'Báo cáo theo phòng ban.', roles: ['admin','student-affairs','japan','training','teacher','dormitory','accounting','japan-partner'], dataPath: 'reports', features: ['Bộ lọc thời gian','KPI','Biểu đồ','Xuất Excel'] },
  { id: 'operations', title: 'Điều hành công việc', group: 'Báo cáo & Điều hành', description: 'Danh sách việc và SLA.', roles: ['admin','student-affairs','training','japan','dormitory','accounting'], dataPath: 'operations', features: ['Kanban','SLA','Phân công','Nhật ký'] },
  { id: 'permissions', title: 'Người dùng & Phân quyền', group: 'Quản trị hệ thống', description: 'Gán role và menu bằng checkbox.', roles: ['admin'], dataPath: 'system/permissions', features: ['Người dùng','Role','Checkbox menu','Lưu realtime'] },
  { id: 'roles', title: 'Vai trò', group: 'Quản trị hệ thống', description: 'Định nghĩa role nghiệp vụ.', roles: ['admin'], dataPath: 'system/roles', features: ['Tạo role','Gán module','Phạm vi dữ liệu','Trạng thái'] },
  { id: 'audit-logs', title: 'Nhật ký hệ thống', group: 'Quản trị hệ thống', description: 'Theo dõi thay đổi và truy cập.', roles: ['admin'], dataPath: 'system/auditLogs', features: ['Lọc sự kiện','Người thao tác','Thời gian','Chi tiết'] },
  { id: 'settings', title: 'Cấu hình', group: 'Quản trị hệ thống', description: 'Cấu hình chung và tích hợp.', roles: ['admin'], dataPath: 'system/settings', features: ['Thông tin đơn vị','Firebase','Thông báo','Sao lưu'] },
]

export function getModule(id: string) { return moduleDefinitions.find((module) => module.id === id) ?? moduleDefinitions[0] }
